# Development environment values
global:
  registry: us-docker.pkg.dev
  imagePrefix: google-samples/containers/gke/boutique
  imageTag: v0.10.1
  pullPolicy: IfNotPresent

namespace: online-boutique-dev

services:
  frontend:
    replicas: 1
    type: NodePort
  
  loadgenerator:
    enabled: false

ingress:
  enabled: false

serviceAccount:
  create: false
  name: "online-boutique"
